---
- name: web application deploy
  hosts: west
  remote_user: hank
  vars:
    workdir: /home/hank/code/src/github.com/aliencyborg/dual-currency
  tasks:
    - name: ensure code/src/github.com/aliencyborg directory is present
      file:
        path: /home/hank/code/src/github.com/aliencyborg
        state: directory

    - name: clone or update dual-currency repository (prod)
      git:
        accept_hostkey: yes
        dest: "{{ workdir }}"
        key_file: /home/hank/.ssh/id_rsa
        repo: "git@github.com:aliencyborg/dual-currency.git"
        update: yes
        version: master

    - name: build docker image
      docker_image:
        force_source: yes
        name: dual-currency
        source: build
        tag: latest
        build:
          path: "{{ workdir }}"
          pull: no

    - name: run docker container
      docker_container:
        expose: 80
        image: dual-currency:latest
        name: dual-currency
        env:
          HSTS: "off"
          LETSENCRYPT_HOST: "dcstage.aliencyb.org"
          PORT: "80"
          VIRTUAL_HOST: "dcstage.aliencyb.org"
